### ISSUE TITLE
BKV_GND missing from approved positions

### ISSUE THREAD

**Issue by erikquinn** [vZMA/ZMA#125]

**Comment by migte** [comment]
Vero Beach, North Perry, and Navy Key are also missing a few.
```
VRB_DEL - 134.975
VRB_GND - 127.450
VRB_TWR - 126.300

HWO_GND - 120.450
HWO_TWR - 132.100

NQX_TWR - 118.575
NQX_GND - 121.700
NQX_DEL - 121.200
```

**Comment by migte** [comment]
North Perry (HWO) is not in the POF file. [Squawk Code Referance](https://www.faa.gov/regulations_policies/orders_notices/index.cfm/go/document.information/documentID/1035828)

(To POF), added: BKV_GND, NQX_DEL

Todo: add to PDF.

**Comment by migte** [comment]
Yeah so right now, pretty much right now everything is done. The airports were added to the approved positions list and POF file was updated. Only exception is North Perry. I added North Perry because I am pretty sure it is a position we are allowed to control, but it isn't in the POF file because I don't know what squawk code ranges to use there. Should probably make another issue for that though, as for BKV ground, I'll push a pr.
