### ISSUE TITLE
Investigate adding FIXES for NAVAIDS to simplify aliases

### ISSUE THREAD

**Issue by FriedrichKayak** [vZMA/ZMA#46]
Currently two aliases are required to display departure fixes when some are FIXES and others are NAVAIDS (because VRC needs to run .fv and .ff). Per Erik's comment on PR #38, suggests this method as compatible with VRC.

Need to consider impact on AIRAC updates and how we can maintain this without regression during update cycles. Probably as easy as simply adding them to the "manual additions" section so they aren't wiped out with AIRAC updates, but this needs investigation and thought.

**Comment by ksnifte** [comment]
Investigated, and it is feasible as described.  PR #47 is up with the changes-- LAL and SRQ now have "fixes" marked so that `.ff LAL SRQ` works.

**Comment by erikquinn** [comment]
In reality, I don't see any reason why all navaids couldn't be added to the fixes list. Means you can .ff anything, less thought required. Still wanna use .fv? It works too!

The extra advantage is that you can make aliases for showing a slew of fixes. In my alias file, I have .sscot5 for example that throws up all the fixes on vERAM, including CYY. I even have them through .srqi14 which shows the fixes on ILS 14 approach into sarasota. World is your oyster when all the vors are in the fixes section, and personally I don't see a downside. This is probably why vERAM doesn't discriminate between fixes/navaids-- because it doesn't matter, and is easily inferred from the 3 vs 5 letter identifiers.

**Comment by ksnifte** [comment]
@erikquinn Sounds reasonable to me.  My only concern is that the labels for fixes and VORs don't perfectly line up, so if you did activate `.ff` and `.fv` at the same time, the VORs would become unreadable since they'd be overlapping.  With the changes above, that issue is still present-- but we decided that it was a price we were willing to pay for 2 VORs that everyone has memorized anyway.

**Comment by erikquinn** [comment]
Right. If you wanted to take it a step further, theoretically you could totally remove the VORs section of the sector file (bear with me)... If you wanted to see the vors, use an alias `.vors` to show them all. Then all of my above still applies and you lose the overlap issue.

The only downside is that the VORs would be the same color as the fixes (since in the eyes of VRC, they _are_ themselves fixes).

Not saying I would take that extra step-- I'd rather have the overlap since I just always keep the view-->VORs turned off, so for me and anyone who does the same, the result would be perfectly good.
